name: 'langgenius::dify-sandbox'

on:
    schedule:
        - cron: '0 20 * * *'
    workflow_dispatch:

jobs:
    ci:
      if: github.repository == 'Loongson-Cloud-Community/container-ci'
      runs-on: self-hosted
      steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Run ci.sh
            run: |
              date
              pushd langgenius/dify-sandbox && ./ci.sh && popd
